import React from "react";

export default function Home() {
  return (
    <div>
      Home
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
      <input />
    </div>
  );
}
